### ISSUE TITLE
Weighted versions of goodness of fit measures?

### ISSUE THREAD

**Issue by rogiersbart** [hzambran/hydroGOF#11]
Hi there,

just a suggestion/question for some enhancement of the package:
Did you consider implementing weighted versions of the goodness of fit measures?
We use hydroGOF as a backend in RMODFLOW (see rogiersbart/RMODFLOW#18) for model performance evaluation, but in groundwater modelling it is common to work with weights that are for instance based on the measurement error. Any thoughts on this? Would this be a useful extension for hydroGOF? Or do you consider this out of scope?

**Comment by hzambran** [comment]
I apologise for my very late reply, but these days have been complicated...

Thank for raising this point, which is perfectly within the scope of hydroGOF.
BTW, thanks for developing RMODFLOW, which is of high interest for many people !!

The only function that currently has implemented the possibility you describe is `NSE`, using the argument `FUN`:

> function to be applied to ‘sim’ and ‘obs’ in order to obtain transformed values thereof before  computing the  Nash-Sutcliffe efficiency.

Is something like:

```
library(hydroGOF)
obs <- 1:10/10
sim <- 2:11/10
w    <- 0.1*obs/sum(0.1*obs)
myfun <- function(x, w) return(x*w)
NSE(sim=sim, obs=obs, FUN=myfun, w=w)
```

what you are looking for?

**Comment by rogiersbart** [comment]
Well, now it's my turn to apologize ...

We are basically looking for inverse-variance weighting, mostly for ME, MAE, MSE and RMSE.
The `FUN` argument of `NSE()` does indeed seem to provide a solution.
Any chance this might be useful to include in the other measures as well?
If not, we can always foresee the weighting at our side of course.

**Comment by hzambran** [comment]
Done in hydroGOF 0.5-0
