### ISSUE TITLE
GOF error

### ISSUE THREAD

**Issue by teaiii** [hzambran/hydroGOF#13]
I have written an R script that calculates all the GOF statistics for a lot of data. I'm getting this error:

Error in if (sd.obs > 0) { : missing value where TRUE/FALSE needed

I know that I have some long runs of '0' obs, not missing, but '0'

What to do? na.rm = TRUE is not the answer.

Thank you,
Tom

**Comment by miguelgcu** [comment]
Hi, did you solve the problem?

_gof_total<-gof(time.serie.raster[,2:7672], time.serie.est[,2:7672],na.rm = TRUE)_
**Error in if (sd.obs > 0) { : missing value where TRUE/FALSE needed**

:/

**Comment by hzambran** [comment]
without a reproducible example it is impossible to analyse this issue.

This should have been solved in the new hydroGOF 0.5-0
