### ISSUE TITLE
Gof error

### ISSUE THREAD

**Issue by miguelgcu** [hzambran/hydroGOF#17]
Hello
I received this error message when executing the gof function.
This is my code and error attached:

_gof_total<-gof(time.serie.raster[,2:7672], time.serie.est[,2:7672],na.rm = TRUE)_
**Error in if (sd.obs > 0) { : missing value where TRUE/FALSE needed**

What is the problem in the case if (sd.obs > 0) ?
My data frames are of precipitation data.

**Comment by hzambran** [comment]
Can you provide a reproducible example?
