### ISSUE TITLE
Goodness of fit  in rstudio

### ISSUE THREAD

**Issue by hiztirab** [hzambran/hydroGOF#2]
[Data.xlsx](https://github.com/hzambran/hydroGOF/files/368297/Data.xlsx)
After arranging data i have applied the gof command as "gof=(sim=simulated, obs= observed)" and got this error.
**warning messages:
1: 'rNSE' can not be computed: some elements in 'obs' are zero ! 
2: 'rd' can not be computed: some elements in 'obs' are zero !**
 I have also applied categorical statistics on this data.
And i used this command "plot(ggof(sim = sim, obs = obs,na.rm=TRUE, ylab = "Q (ft3/day)",
     ftype =c("seasonal"),FUN=mean))" to draw the figures.
same issues are getting here.

**Comment by hzambran** [comment]
Dear hiztirab,

could you be specific about the _issues_ that you found there?

the `ggof` function automatically produces a plot to the current graphical device, and therefore there is no need to call it within a `plot` command.
