### ISSUE TITLE
hydroGOF & hydroTSM no longer available through CRAN

### ISSUE THREAD

**Issue by jd-2001** [hzambran/hydroGOF#20]
Hello Mauricio,

Recently, I have started receiving error messages when installing hydroGOF and hydroTSM from CRAN.  It says they have been archived due to their dependency on maptools, which was also archived on 2023-10-16.  I assume this is a known issue, but I wanted to inquire as to whether you had a tentative timeline for removing that dependency and making them available again on CRAN?  

Thank you for creating these packages because they have been extremely helpful in my work.

**Comment by hzambran** [comment]
Hi jd-2001,

I'm aware that `hydroGOF` and `hydroTSM` were removed from **CRAN**, but thank you very much for your concern.

I'm working hard in the new versions of the two packages (new functions, improvements and bugfixes), and I hope to submit `hydroTSM` by December 2nd, and `hydroGOF` the week after.

Meanwhile, you can install both packages from github:

```
if (!require(devtools)) install.packages("devtools")
library(devtools)
install_github("hzambran/hydroTSM")
install_github("hzambran/hydroGOF")

```

**Comment by jd-2001** [comment]
Thank you for the follow-up because that is great news.  We are glad to hear that we will still be able to use it for our model calibration utilities.

We appreciate the time & effort that you have spent developing these packages.

-John

**Comment by hzambran** [comment]
hydroTSM and hydroGOF are back on CRAN now:

https://cran.r-project.org/package=hydroTSM
https://cran.r-project.org/package=hydroGOF

hydroPSO is comming...

**Comment by jd-2001** [comment]
Thank you for the update.  I will let others in my research group know.

I appreciate you making this fix so quickly.

-John
