### ISSUE TITLE
Error: 'wNSE' is not an exported object from 'namespace:hydroGOF'

### ISSUE THREAD

**Issue by shulele** [hzambran/hydroGOF#21]
I am trying to use the wNSE() function but have failed. 
The version of hydroGOF is ‘0.5.5’.

Code :
```

library(hydroGOF)
packageVersion("hydroGOF")
##################
# Example 1: basic ideal case
obs <- 1:10
sim <- 1:10
hydroGOF::wNSE(sim, obs)

```

Error:

Error: 'wNSE' is not an exported object from 'namespace:hydroGOF'

**Comment by hzambran** [comment]
The latest version of hydroGOF is 0.5-4, and I don't get any error when running your code.
Can you supply a different example?
