### ISSUE TITLE
Error for pbias equation

### ISSUE THREAD

**Issue by bijoychandraAU** [hzambran/hydroGOF#22]
According to  Moriasi et al. (2007)-MODEL EVALUATION GUIDELINES FOR SYSTEMATIC QUANTIFICATION OF ACCURACY IN WATERSHED SIMULATIONS, the **pbias** equation needs to subtract simulated data from observed value. 
Thank you

**Comment by hzambran** [comment]
The **pbias** was not proposed by Moriasi et al. (2007), but rather it was proposed by:

* Yapo, P. O.; Gupta, H. V.; Sorooshian S. (1996). Automatic calibration of conceptual rainfall-runoff models: sensitivity to calibration data. Journal of Hydrology. v181 i1-4. 23-48. doi:10.1016/0022-1694(95)02918-4.

* Sorooshian, S., Q. Duan, and V. K. Gupta. 1993. Calibration of rainfall-runoff models: Application of global optimization to the Sacramento Soil Moisture Accounting Model, Water Resources Research, 29 (4), 1185-1194, doi:10.1029/92WR02617.

The use Qsim - Jobs, which is much easier to interpret that the other way around.
