### ISSUE TITLE
Library "hydroGOF" failed to load

### ISSUE THREAD

**Issue by vrao1** [hzambran/hydroGOF#6]
> library(hydroGOF)
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

I wrote following program:

install.packages("hydroGOF", repos = "http://cran.r-project.org/")

library(hydroGOF)
library(PSF)

p <- psf(nottem)
a <- predict(p, n.ahead = 12)
a

> install.packages("hydroGOF", repos = "http://cran.r-project.org/")
Installing package into ‘/home/vinodrao/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'http://cran.r-project.org/src/contrib/hydroGOF_0.3-10.tar.gz'
Content type 'application/x-gzip' length 545075 bytes (532 KB)
==================================================
downloaded 532 KB

* installing *source* package ‘hydroGOF’ ...
** package ‘hydroGOF’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (hydroGOF)

The downloaded source packages are in
	‘/tmp/RtmpxILLDO/downloaded_packages’
> 
> library(hydroGOF)
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

> library(PSF)
Error in library(PSF) : there is no package called ‘PSF’
> 
> p <- psf(nottem)
Error in psf(nottem) : could not find function "psf"
> a <- predict(p, n.ahead = 12)
Error in predict(p, n.ahead = 12) : object 'p' not found
> a
Error: object 'a' not found

**Comment by jthurner** [comment]
hydroGOF loads without problems, it's PSF which fails to load:

    library(PSF)
    Error in library(PSF) : there is no package called ‘PSF’

did you just forget to install the PSF package?
