### ISSUE TITLE
ggof plotting error

### ISSUE THREAD

**Issue by hasabchy** [hzambran/hydroGOF#7]
Hi,
My ggof code showing error for dates. May anybody help me in this regard? Here is my code and the data file are attached
flows=read.csv("E:/flow_sub1_sim2005_10.csv",header = T)
flows=data.frame(jday=mdy.date(flows$Month,flows$Day,flows$year),flows)
Simulated=flows$basinflow.1.
Observed=flows$Observed
ggof(Simulated, Observed,dates=flows$Date , main=" "
,ylab=expression(paste("Q, [m"^"3","/s]")),xlab="",ftype="seasonal",FUN=mean)
The error is here:
Error in .External.graphics(C_layout, num.rows, num.cols, mat, as.integer(num.figures), :
invalid graphics state
In addition: Warning message:
In if (is.na(match(class(dates), c("character", "factor", "Date", :
the condition has length > 1 and only the first element will be used

**Comment by hzambran** [comment]
Dear @hasabchy,

You did not provide a reproducible example. If you can provide a minimal and reproducible example, please open a new issue.
